name: Testing Gameloan Software

on: [push]

jobs:
  build:
    name: Maven Build
    strategy:
        matrix:
          os: [macos-latest, ubuntu-latest, windows-latest]
  
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v3
        - name: Setup Java 17
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'temurin'
            cache: 'maven'
        - name: Build with Maven
          run: ./mvnw verify

    